<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.zongoforspeed</groupId>
    <artifactId>AdventOfCode</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Advent Of Code</name>
    <modules>
        <module>common</module>
        <module>common-test</module>
        <module>year2015</module>
        <module>year2016</module>
        <module>year2017</module>
        <module>year2018</module>
        <module>year2019</module>
        <module>year2020</module>
        <module>year2021</module>
        <module>year2022</module>
        <module>year2023</module>
        <module>year2024</module>
        <module>year2025</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>

        <!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-classic -->
        <logback-classic.version>1.5.32</logback-classic.version>

        <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
        <slf4j.version>2.0.17</slf4j.version>

        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
        <commons-lang3.version>3.20.0</commons-lang3.version>

        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
        <commons-collections4.version>4.5.0</commons-collections4.version>

        <!-- https://mvnrepository.com/artifact/commons-io/commons-io -->
        <commons-io.version>2.22.0</commons-io.version>

        <!-- https://mvnrepository.com/artifact/org.apache.commons/commons-math3 -->
        <commons-math3.version>3.6.1</commons-math3.version>

        <!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
        <guava.version>33.6.0-jre</guava.version>

        <!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
        <gson.version>2.14.0</gson.version>

        <!-- https://mvnrepository.com/artifact/it.unimi.dsi/fastutil -->
        <fastutil.version>8.5.18</fastutil.version>

        <!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
        <commons-codec.version>1.22.0</commons-codec.version>

        <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-engine -->
        <junit-jupiter.version>6.0.3</junit-jupiter.version>

        <!-- https://mvnrepository.com/artifact/org.assertj/assertj-core -->
        <assertj.version>3.27.7</assertj.version>

        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
        <maven-surefire-plugin.version>3.5.5</maven-surefire-plugin.version>

        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>

        <!-- https://mvnrepository.com/artifact/com.google.errorprone/error_prone_core -->
        <error-prone.version>2.49.0</error-prone.version>

        <!-- https://mvnrepository.com/artifact/com.uber.nullaway/nullaway -->
        <nullaway.version>0.13.4</nullaway.version>

        <!-- https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-core -->
        <jmh.version>1.37</jmh.version>

        <!-- Source: https://mvnrepository.com/artifact/org.jspecify/jspecify -->
        <jspecify.version>1.0.0</jspecify.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>common</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>common-test</artifactId>
                <version>${project.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2015</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2016</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2017</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2018</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2019</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2020</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2021</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2022</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2023</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2024</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.zongoforspeed</groupId>
                <artifactId>year2025</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>

            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback-classic.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>${commons-lang3.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons-collections4.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>

            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>

            <dependency>
                <groupId>it.unimi.dsi</groupId>
                <artifactId>fastutil</artifactId>
                <version>${fastutil.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${commons-codec.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-math3</artifactId>
                <version>${commons-math3.version}</version>
            </dependency>

            <dependency>
                <groupId>org.jspecify</groupId>
                <artifactId>jspecify</artifactId>
                <version>${jspecify.version}</version>
                <scope>compile</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit-jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit-jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-params -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${junit-jupiter.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/org.openjdk.jmh/jmh-core -->
            <dependency>
                <groupId>org.openjdk.jmh</groupId>
                <artifactId>jmh-core</artifactId>
                <version>${jmh.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.openjdk.jmh</groupId>
                <artifactId>jmh-generator-annprocess</artifactId>
                <version>${jmh.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <showDeprecation>true</showDeprecation>
                    <showWarnings>true</showWarnings>
                    <compilerArgs>
                        <arg>-XDcompilePolicy=simple</arg>
                        <arg>--should-stop=ifError=FLOW</arg>
                        <arg>
                            -Xplugin:ErrorProne
                            -XepExcludedPaths:.*/target/(generated-sources|generated-test-sources)/.*
                            -Xep:NullAway:ERROR
                            -XepOpt:NullAway:AnnotatedPackages=com.adventofcode
                            -XepOpt:NullAway:JSpecifyMode=true
                            -Xep:MissingOverride:ERROR
                            -Xep:EqualsGetClass:ERROR
                            -Xep:StringSplitter:ERROR
                            -Xep:ReferenceEquality:ERROR
                            -Xep:LoopOverCharArray:ERROR
                            -Xep:DefaultCharset:OFF
                            -Xep:IntLongMath:ERROR
                            -Xep:FutureReturnValueIgnored:OFF
                            -Xep:NullOptional:ERROR
                            -Xep:NullableConstructor:ERROR
                            -Xep:NullableOptional:ERROR
                            -Xep:NullablePrimitive:ERROR
                            -Xep:NullablePrimitiveArray:ERROR
                            -Xep:NullableTypeParameter:ERROR
                            -Xep:NullableVoid:ERROR
                            -Xep:NullableWildcard:ERROR
                            -Xep:UnusedMethod:ERROR
                            -Xep:UnusedVariable:ERROR
                            -Xep:UnusedNestedClass:ERROR
                            -Xep:BoxedPrimitiveConstructor:ERROR
                            -Xep:MathAbsoluteRandom:ERROR
                            -Xep:OptionalEquality:ERROR
                            -Xep:StreamResourceLeak:ERROR
                            -Xep:ArgumentSelectionDefectChecker:ERROR
                            -Xep:AssertEqualsArgumentOrderChecker:ERROR
                            -Xep:BadInstanceof:ERROR
                            -Xep:ComparisonOutOfRange:ERROR
                            -Xep:DoubleBraceInitialization:ERROR
                            -Xep:DuplicateMapKeys:ERROR
                            -Xep:EqualsIncompatibleType:ERROR
                            -Xep:FormatString:ERROR
                            -Xep:InvalidBlockTag:ERROR
                            -Xep:InvalidInlineTag:ERROR
                            -Xep:InvalidParam:ERROR
                            -Xep:InvalidThrows:ERROR
                            -Xep:JavaDurationWithNanos:ERROR
                            -Xep:JavaDurationWithSeconds:ERROR
                            -Xep:JavaInstantGetSecondsGetNano:ERROR
                            -Xep:JavaLocalDateTimeGetNano:ERROR
                            -Xep:JavaLocalTimeGetNano:ERROR
                            -Xep:JavaTimeDefaultTimeZone:ERROR
                            -Xep:LockOnBoxedPrimitive:ERROR
                            -Xep:ModifiedButNotUsed:ERROR
                            -Xep:ModifyCollectionInEnhancedForLoop:ERROR
                            -Xep:ModifySourceCollectionInStream:ERROR
                            -Xep:MultipleParallelOrSequentialCalls:ERROR
                            -Xep:MutableConstantField:ERROR
                            -Xep:MutablePublicArray:ERROR
                            -Xep:NonCanonicalType:ERROR
                            -Xep:ObjectToString:ERROR
                            -Xep:OperatorPrecedence:ERROR
                            -Xep:PreconditionsCheckNotNullPrimitive:ERROR
                            -Xep:RandomModInteger:ERROR
                            -Xep:ReturnValueIgnored:ERROR
                            -Xep:SelfAssignment:ERROR
                            -Xep:SelfComparison:ERROR
                            -Xep:SelfEquals:ERROR
                            -Xep:ShortCircuitBoolean:ERROR
                            -Xep:StaticAssignmentInConstructor:ERROR
                            -Xep:StaticGuardedByInstance:ERROR
                            -Xep:SynchronizeOnNonFinalField:ERROR
                            -Xep:ThreadJoinLoop:ERROR
                            -Xep:ThreadLocalUsage:ERROR
                            -Xep:WaitNotInLoop:ERROR
                            -Xep:EmptyBlockTag:ERROR
                            -Xep:EmptyCatch:ERROR
                            -Xep:InvalidThrows:ERROR
                            -Xep:NonCanonicalStaticMemberImport:ERROR
                            -Xep:ArrayAsKeyOfSetOrMap:ERROR
                            -Xep:AssertFalse:ERROR
                            -Xep:CanIgnoreReturnValueSuggester:OFF
                            -Xep:ClassName:ERROR
                            -Xep:ComparisonContractViolated:ERROR
                            -Xep:DepAnn:ERROR
                            -Xep:EmptyIf:ERROR
                            -Xep:IterablePathParameter:ERROR
                            -Xep:LongLiteralLowerCaseSuffix:ERROR
                            -Xep:NumericEquality:ERROR
                            -Xep:ParameterName:ERROR
                            -Xep:PrimitiveAtomicReference:ERROR
                            -Xep:StaticAssignmentInConstructor:ERROR
                            -Xep:SystemExitOutsideMain:ERROR
                            -Xep:TypeParameterNaming:ERROR
                            -Xep:UnnecessaryAssignment:ERROR
                            -Xep:UnnecessaryCheckNotNull:ERROR
                            -Xep:UnnecessaryParentheses:ERROR
                            -Xep:UnusedException:ERROR
                        </arg>
                    </compilerArgs>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>${error-prone.version}</version>
                        </path>
                        <path>
                            <groupId>com.uber.nullaway</groupId>
                            <artifactId>nullaway</artifactId>
                            <version>${nullaway.version}</version>
                        </path>
                        <path>
                            <groupId>org.openjdk.jmh</groupId>
                            <artifactId>jmh-generator-annprocess</artifactId>
                            <version>${jmh.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>6.28.0</version>
                <configuration>
                    <exportDatatables>true</exportDatatables>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.migrate.UpgradeToJava25</recipe>
                    </activeRecipes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-migrate-java</artifactId>
                        <version>3.26.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>