package com.adventofcode.year2025;

import com.adventofcode.common.utils.LongPair;
import it.unimi.dsi.fastutil.ints.Int2LongArrayMap;
import it.unimi.dsi.fastutil.ints.Int2LongMap;

import java.util.Scanner;

public final class Day07 {

    /**
     * --- Day 7: Laboratories ---
     * <p>
     * You thank the cephalopods for the help and exit the trash compactor,
     * finding yourself in the familiar halls of a North Pole research wing.
     * <p>
     * Based on the large sign that says "teleporter hub", they seem to be
     * researching teleportation; you can't help but try it for yourself and step
     * onto the large yellow teleporter pad.
     * <p>
     * Suddenly, you find yourself in an unfamiliar room! The room has no doors;
     * the only way out is the teleporter. Unfortunately, the teleporter seems to
     * be leaking magic smoke.
     * <p>
     * Since this is a teleporter lab, there are lots of spare parts, manuals, and
     * diagnostic equipment lying around. After connecting one of the diagnostic
     * tools, it helpfully displays error code 0H-N0, which apparently means that
     * there's an issue with one of the tachyon manifolds.
     * <p>
     * You quickly locate a diagram of the tachyon manifold (your puzzle input). A
     * tachyon beam enters the manifold at the location marked S; tachyon beams
     * always move downward. Tachyon beams pass freely through empty space (.).
     * However, if a tachyon beam encounters a splitter (^), the beam is stopped;
     * instead, a new tachyon beam continues from the immediate left and from the
     * immediate right of the splitter.
     * <p>
     * For example:
     * <p>
     * .......S.......
     * ...............
     * .......^.......
     * ...............
     * ......^.^......
     * ...............
     * .....^.^.^.....
     * ...............
     * ....^.^...^....
     * ...............
     * ...^.^...^.^...
     * ...............
     * ..^...^.....^..
     * ...............
     * .^.^.^.^.^...^.
     * ...............
     * <p>
     * In this example, the incoming tachyon beam (|) extends downward from S
     * until it reaches the first splitter:
     * <p>
     * .......S.......
     * .......|.......
     * .......^.......
     * ...............
     * ......^.^......
     * ...............
     * .....^.^.^.....
     * ...............
     * ....^.^...^....
     * ...............
     * ...^.^...^.^...
     * ...............
     * ..^...^.....^..
     * ...............
     * .^.^.^.^.^...^.
     * ...............
     * <p>
     * At that point, the original beam stops, and two new beams are emitted from
     * the splitter:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^|......
     * ...............
     * ......^.^......
     * ...............
     * .....^.^.^.....
     * ...............
     * ....^.^...^....
     * ...............
     * ...^.^...^.^...
     * ...............
     * ..^...^.....^..
     * ...............
     * .^.^.^.^.^...^.
     * ...............
     * <p>
     * Those beams continue downward until they reach more splitters:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^|......
     * ......|.|......
     * ......^.^......
     * ...............
     * .....^.^.^.....
     * ...............
     * ....^.^...^....
     * ...............
     * ...^.^...^.^...
     * ...............
     * ..^...^.....^..
     * ...............
     * .^.^.^.^.^...^.
     * ...............
     * <p>
     * At this point, the two splitters create a total of only three tachyon
     * beams, since they are both dumping tachyons into the same place between
     * them:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^|......
     * ......|.|......
     * .....|^|^|.....
     * ...............
     * .....^.^.^.....
     * ...............
     * ....^.^...^....
     * ...............
     * ...^.^...^.^...
     * ...............
     * ..^...^.....^..
     * ...............
     * .^.^.^.^.^...^.
     * ...............
     * <p>
     * This process continues until all of the tachyon beams reach a splitter or
     * exit the manifold:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^|......
     * ......|.|......
     * .....|^|^|.....
     * .....|.|.|.....
     * ....|^|^|^|....
     * ....|.|.|.|....
     * ...|^|^|||^|...
     * ...|.|.|||.|...
     * ..|^|^|||^|^|..
     * ..|.|.|||.|.|..
     * .|^|||^||.||^|.
     * .|.|||.||.||.|.
     * |^|^|^|^|^|||^|
     * |.|.|.|.|.|||.|
     * <p>
     * To repair the teleporter, you first need to understand the beam-splitting
     * properties of the tachyon manifold. In this example, a tachyon beam is
     * split a total of 21 times.
     * <p>
     * Analyze your manifold diagram. How many times will the beam be split?
     * <p>
     * --- Part Two ---
     * <p>
     * With your analysis of the manifold complete, you begin fixing the
     * teleporter. However, as you open the side of the teleporter to replace the
     * broken manifold, you are surprised to discover that it isn't a classical
     * tachyon manifold - it's a quantum tachyon manifold.
     * <p>
     * With a quantum tachyon manifold, only a single tachyon particle is sent
     * through the manifold. A tachyon particle takes both the left and right path
     * of each splitter encountered.
     * <p>
     * Since this is impossible, the manual recommends the many-worlds
     * interpretation of quantum tachyon splitting: each time a particle reaches a
     * splitter, it's actually time itself which splits. In one timeline, the
     * particle went left, and in the other timeline, the particle went right.
     * <p>
     * To fix the manifold, what you really need to know is the number of
     * timelines active after a single particle completes all of its possible
     * journeys through the manifold.
     * <p>
     * In the above example, there are many timelines. For instance, there's the
     * timeline where the particle always went left:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^.......
     * ......|........
     * .....|^.^......
     * .....|.........
     * ....|^.^.^.....
     * ....|..........
     * ...|^.^...^....
     * ...|...........
     * ..|^.^...^.^...
     * ..|............
     * .|^...^.....^..
     * .|.............
     * |^.^.^.^.^...^.
     * |..............
     * <p>
     * Or, there's the timeline where the particle alternated going left and right
     * at each splitter:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^.......
     * ......|........
     * ......^|^......
     * .......|.......
     * .....^|^.^.....
     * ......|........
     * ....^.^|..^....
     * .......|.......
     * ...^.^.|.^.^...
     * .......|.......
     * ..^...^|....^..
     * .......|.......
     * .^.^.^|^.^...^.
     * ......|........
     * <p>
     * Or, there's the timeline where the particle ends up at the same point as
     * the alternating timeline, but takes a totally different path to get there:
     * <p>
     * .......S.......
     * .......|.......
     * ......|^.......
     * ......|........
     * .....|^.^......
     * .....|.........
     * ....|^.^.^.....
     * ....|..........
     * ....^|^...^....
     * .....|.........
     * ...^.^|..^.^...
     * ......|........
     * ..^..|^.....^..
     * .....|.........
     * .^.^.^|^.^...^.
     * ......|........
     * <p>
     * In this example, in total, the particle ends up on 40 different timelines.
     * <p>
     * Apply the many-worlds interpretation of quantum tachyon splitting to your
     * manifold diagram. In total, how many different timelines would a single
     * tachyon particle end up on?
     */
    private Day07() {
        // No-Op
    }

    public static LongPair countTimeline(Scanner scanner) {
        long split = 0;
        Int2LongMap beams = new Int2LongArrayMap();
        int n = 0;
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            if (n == 0) {
                int i = line.indexOf('S');
                if (i != -1) {
                    beams.put(i, 1L);
                } else {
                    System.out.println("Cannot find starting position in input");
                }
            } else {
                Int2LongMap toAdd = new Int2LongArrayMap();
                for (int i = 0; i < line.length(); i++) {
                    char c = line.charAt(i);
                    if (c == '^') {
                        long value = beams.remove(i);
                        if (value != beams.defaultReturnValue()) {
                            split += 1;
                            toAdd.put(i - 1, toAdd.getOrDefault(i - 1, 0L) + value);
                            toAdd.put(i + 1, toAdd.getOrDefault(i + 1, 0L) + value);
                        }
                    }
                }
                for (Int2LongMap.Entry entry : toAdd.int2LongEntrySet()) {
                    beams.put(entry.getIntKey(), beams.getOrDefault(entry.getIntKey(), 0L) + entry.getLongValue());
                }
            }
            n++;
        }
        long timeline = beams.values().longStream().sum();
        return new LongPair(split, timeline);
    }
}
